include: 'https://gitlab.com/mateuszwojt/ci-templates/raw/main/.before-script-template.yml'

stages:
  - build
  - upload
  - release
  - deploy

variables:
  PACKAGE_VERSION: "0.9.2"
  PLUGIN_NAME: "denoiser"
  PLUGIN_RELEASE_NAME: "${PLUGIN_NAME}-${PACKAGE_VERSION}"
  PLUGIN_RELEASE_NAME_LINUX: "${PLUGIN_RELEASE_NAME}.linux"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/NukeCGDenoiser/${PACKAGE_VERSION}"


build:
  stage: build
  image: centos:7.8.2003
  script:
    - chmod +x build.sh
    - ./build.sh
    - cd build && tar -cvzf ${PLUGIN_RELEASE_NAME_LINUX}.tar.gz ${PLUGIN_NAME}.so menu.py && cd ..
  artifacts:
    paths:
      - build/${PLUGIN_NAME}.so
      - build/${PLUGIN_RELEASE_NAME_LINUX}.tar.gz

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/${PLUGIN_RELEASE_NAME_LINUX}.tar.gz "${PACKAGE_REGISTRY_URL}/${PLUGIN_RELEASE_NAME_LINUX}.tar.gz"

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"${PLUGIN_RELEASE_NAME}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PLUGIN_RELEASE_NAME_LINUX}.tar.gz\"}"

pages:
  stage: deploy
  image: python:3.7-alpine
  script:
    - pip install -U sphinx
    - sphinx-build -b html . public
  artifacts:
    paths:
    - public
  only:
  - master

make-badge:
  stage: deploy
  script:
    - version=$(cat VERSION.txt)
    - version_badge_id=$(curl --header "PRIVATE-TOKEN:${API_TOKEN}" https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/badges | jq -c 'map(select(.name | contains("version")))[0].id')
    - curl --request PUT --header "PRIVATE-TOKEN:${API_TOKEN}" --data "image_url=https://img.shields.io/badge/version-${version}-blue" https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/badges/${version_badge_id}
  only:
  - master