# using official CentOS 8 image
image: centos:8

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - yum -y install epel-release
  - yum -y update
  - yum -y install cmake3 gcc gcc-c++ make wget unzip
  - yum -y install freeglut freeglut-devel libXi-devel libXrandr-devel libXinerama-devel libXcursor-devel
  - yum -y install tbb-devel
  - yum -y clean all

build:
  stage: build
  script:
    - chmod +x build.sh
    - ./build.sh
  artifacts:
    paths:
      - build/
