name: Build plugins
on:
  pull_request:

env:
  image: ghcr.io/gillesvink/nukedockerbuild

jobs:

  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        nuke_version: ["14.1", "15.0"]
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - name: Download OpenImageDenoise
        run: |
          Invoke-WebRequest -Uri "https://github.com/OpenImageDenoise/oidn/releases/download/v2.1.0/oidn-2.1.0.x64.windows.zip" -OutFile "C:\oidn-2.1.0.x64.windows.zip"
          Expand-Archive "C:\oidn-2.1.0.x64.windows.zip" -DestinationPath "${{ github.workspace }}" -Verbose

      - name: Pull image
        run: docker pull ${{ env.image }}:${{ matrix.nuke_version }}-windows-latest

      - name: Run build
        run: docker run --rm -v "${{ github.workspace }}:C:\nuke_build_directory" ${{ env.image }}:${{ matrix.nuke_version }}-windows-latest powershell -Command "cmake . -DCMAKE_GENERATOR_PLATFORM=x64 -B build ; cmake --build build --config Release"

      - uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.nuke_version }}
          path: ${{ github.workspace }}/build/lib/Release
